### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by Geervan** [Sudheer121/Study-Room#3]
I am not able to run it locally after npm install and when I run npm start I get the error start  npm ERR! missing script: start  
 I tried starting from the package.json but when I successfully started it and viewed it in localhost3000 I am getting such as  'react-scripts' is not recognized as an internal or external command, operable program or batch file and a suggestion yyou can also update readme.md so that it will be helpful to people 
 please help me thank you

**Comment by dumbbellcode** [comment]
I have added installation and pull request instructions in the ReadMe, let me know if you still need help. Closing this issue.
