### ISSUE TITLE
An extensive problem for my previous issue

### ISSUE THREAD

**Issue by Geervan** [Sudheer121/Study-Room#4]
I followed your procedure and the server folder(node index.js) works fine but when I do npm start in client folder I get this error 

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.    

The react-scripts package provided by Create React App requires a dependency:

  "webpack-dev-server": "3.11.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack-dev-server was detected higher up in the tree:

  C:\Users\Lenovo\node_modules\webpack-dev-server (version: 3.11.1)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "webpack-dev-server" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\Lenovo\node_modules\webpack-dev-server is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls webpack-dev-server in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed webpack-dev-server.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code 1
npm ERR! path C:\Users\Lenovo\Desktop\Video\Study-Room-main\client
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c react-scripts start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2021-03-06T07_52_04_228Z-debug.log

Thank you in advance and I had a doubt if I comment the twilio part of code the project should run without the twilio api's and sdk right

**Comment by dumbbellcode** [comment]
The dependency 'webpack-dev-server' in the project conflicts with the one installed globally on your computer, hence this issue is not related to the project. I cloned it on my end and it works fine. 
Anyways, here's a [fix ](https://stackoverflow.com/questions/56528222/npm-start-returns-error-there-might-be-a-problem-with-the-project-dependency-t#:~:text=guess%20this%20issue%3A-,There%20might%20be%20a%20problem%20with%20the%20project%20dependency%20tree,you%20need%20to%20fix%20locally.&text=Manually%20installing%20incompatible%20versions%20is,hard%2Dto%2Ddebug%20issues.&text=Delete%20node_modules%20in%20your%20project%20folder). 
Keep learning !!!

**Comment by Geervan** [comment]
Ok Thanks but Now the interface is coming but when I join a room I am not able to chat and it isnt showing the people who are online  is it my local problem ?

**Comment by dumbbellcode** [comment]
You need to spend some time working with Node projects
