### ISSUE TITLE
Websocket error while running the app , also existing users don't load on page refresh 

### ISSUE THREAD

**Issue by Anonymous3-cpu** [Sudheer121/Study-Room#5]
WebSocket connection to 'wss://localhost:5000/socket.io/?EIO=3&transport=websocket&sid=UxButrskHWm9Lp1aAAAA' failed: Invalid frame header.
Also users don't load on page refresh.
Please Help !!
I am learning Webrtc and you have implemented it successfully. Please Guide me. It would be my honour to learn webrtc from you.

**Comment by dumbbellcode** [comment]
Users do load on page refresh, check out the linked website https://mystudyroom.netlify.app and try reloading. 
I have mentioned the related resources in readme of the repo, you may checkout [my blog](https://sudheer.hashnode.dev/how-multimedia-streaming-apps-work) which is an intro to websockets and webrtc.

**Comment by Anonymous3-cpu** [comment]
I have checked all of it still I'm facing the same issue. Can you help me debug it
