### ISSUE TITLE
Facing the same issue

### ISSUE THREAD

**Issue by Anonymous3-cpu** [Sudheer121/Study-Room#6]
I am facing the same issue. I have checked your website. I have tried the mentioned steps in readme. I have tried the server side part of your code, Still I'm facing the same isssue. Please can you help me debug it . When I try to run your repo locally users don't reload and I face an Invalid Frame Header issue as well. Have you made changes while hosting the server side of the code because that github repo I tried to run locally does't load users , but your website does them well. Please guide me

**Comment by dumbbellcode** [comment]
Hey @Anonymous3-cpu, I cloned the repo separately just to make sure if it's working right, I have updated some environment variables in .env.example, just do a `git pull` and copy the contents from `.env.example`  to ` .env ` for both client and server. Let me know if you still have issues, play around with environment variables and you'll get what's happening

**Comment by Anonymous3-cpu** [comment]
The issue is whenever I reload the Client side it shows the error Username is already taken but which does'nt allow the users to reload, Although there is no person with same name. I have to reload like twice or thrice for users to load back again.

**Comment by Anonymous3-cpu** [comment]
Please help me fix this issue. It would be really helpful

**Comment by dumbbellcode** [comment]
> The issue is whenever I reload the Client side it shows the error Username is already taken but which does'nt allow the users to reload, Although there is no person with same name. I have to reload like twice or thrice for users to load back again.

I haven't introduced uuid or user authentication for uniquely identifying users, hence try joining with different names, I'll make the required changes in few days. Works fine for different names, look at the console for error you are getting if it doesn't work

**Comment by dumbbellcode** [comment]
Above MR solves this issue, readme has been updated for installation. Will push another MR for username issue.
